/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProRouteImport } from './routes/pro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup.index'
import { Route as SignupProRouteImport } from './routes/signup.pro'
import { Route as ConnectExtensionRouteImport } from './routes/connect.extension'
import { Route as BillingManageRouteImport } from './routes/billing.manage'
import { Route as ConnectExtensionIndexRouteImport } from './routes/connect.extension.index'
import { Route as ConnectExtensionSuccessRouteImport } from './routes/connect.extension.success'
import { Route as ConnectExtensionFailureRouteImport } from './routes/connect.extension.failure'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignupRoute,
} as any)
const SignupProRoute = SignupProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => SignupRoute,
} as any)
const ConnectExtensionRoute = ConnectExtensionRouteImport.update({
  id: '/connect/extension',
  path: '/connect/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingManageRoute = BillingManageRouteImport.update({
  id: '/billing/manage',
  path: '/billing/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectExtensionIndexRoute = ConnectExtensionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectExtensionRoute,
} as any)
const ConnectExtensionSuccessRoute = ConnectExtensionSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ConnectExtensionRoute,
} as any)
const ConnectExtensionFailureRoute = ConnectExtensionFailureRouteImport.update({
  id: '/failure',
  path: '/failure',
  getParentRoute: () => ConnectExtensionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pro': typeof ProRoute
  '/signup': typeof SignupRouteWithChildren
  '/upgrade': typeof UpgradeRoute
  '/billing/manage': typeof BillingManageRoute
  '/connect/extension': typeof ConnectExtensionRouteWithChildren
  '/signup/pro': typeof SignupProRoute
  '/signup/': typeof SignupIndexRoute
  '/connect/extension/failure': typeof ConnectExtensionFailureRoute
  '/connect/extension/success': typeof ConnectExtensionSuccessRoute
  '/connect/extension/': typeof ConnectExtensionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pro': typeof ProRoute
  '/upgrade': typeof UpgradeRoute
  '/billing/manage': typeof BillingManageRoute
  '/signup/pro': typeof SignupProRoute
  '/signup': typeof SignupIndexRoute
  '/connect/extension/failure': typeof ConnectExtensionFailureRoute
  '/connect/extension/success': typeof ConnectExtensionSuccessRoute
  '/connect/extension': typeof ConnectExtensionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pro': typeof ProRoute
  '/signup': typeof SignupRouteWithChildren
  '/upgrade': typeof UpgradeRoute
  '/billing/manage': typeof BillingManageRoute
  '/connect/extension': typeof ConnectExtensionRouteWithChildren
  '/signup/pro': typeof SignupProRoute
  '/signup/': typeof SignupIndexRoute
  '/connect/extension/failure': typeof ConnectExtensionFailureRoute
  '/connect/extension/success': typeof ConnectExtensionSuccessRoute
  '/connect/extension/': typeof ConnectExtensionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pro'
    | '/signup'
    | '/upgrade'
    | '/billing/manage'
    | '/connect/extension'
    | '/signup/pro'
    | '/signup/'
    | '/connect/extension/failure'
    | '/connect/extension/success'
    | '/connect/extension/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pro'
    | '/upgrade'
    | '/billing/manage'
    | '/signup/pro'
    | '/signup'
    | '/connect/extension/failure'
    | '/connect/extension/success'
    | '/connect/extension'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/pro'
    | '/signup'
    | '/upgrade'
    | '/billing/manage'
    | '/connect/extension'
    | '/signup/pro'
    | '/signup/'
    | '/connect/extension/failure'
    | '/connect/extension/success'
    | '/connect/extension/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProRoute: typeof ProRoute
  SignupRoute: typeof SignupRouteWithChildren
  UpgradeRoute: typeof UpgradeRoute
  BillingManageRoute: typeof BillingManageRoute
  ConnectExtensionRoute: typeof ConnectExtensionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/pro': {
      id: '/signup/pro'
      path: '/pro'
      fullPath: '/signup/pro'
      preLoaderRoute: typeof SignupProRouteImport
      parentRoute: typeof SignupRoute
    }
    '/connect/extension': {
      id: '/connect/extension'
      path: '/connect/extension'
      fullPath: '/connect/extension'
      preLoaderRoute: typeof ConnectExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/manage': {
      id: '/billing/manage'
      path: '/billing/manage'
      fullPath: '/billing/manage'
      preLoaderRoute: typeof BillingManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/extension/': {
      id: '/connect/extension/'
      path: '/'
      fullPath: '/connect/extension/'
      preLoaderRoute: typeof ConnectExtensionIndexRouteImport
      parentRoute: typeof ConnectExtensionRoute
    }
    '/connect/extension/success': {
      id: '/connect/extension/success'
      path: '/success'
      fullPath: '/connect/extension/success'
      preLoaderRoute: typeof ConnectExtensionSuccessRouteImport
      parentRoute: typeof ConnectExtensionRoute
    }
    '/connect/extension/failure': {
      id: '/connect/extension/failure'
      path: '/failure'
      fullPath: '/connect/extension/failure'
      preLoaderRoute: typeof ConnectExtensionFailureRouteImport
      parentRoute: typeof ConnectExtensionRoute
    }
  }
}

interface SignupRouteChildren {
  SignupProRoute: typeof SignupProRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupProRoute: SignupProRoute,
  SignupIndexRoute: SignupIndexRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

interface ConnectExtensionRouteChildren {
  ConnectExtensionFailureRoute: typeof ConnectExtensionFailureRoute
  ConnectExtensionSuccessRoute: typeof ConnectExtensionSuccessRoute
  ConnectExtensionIndexRoute: typeof ConnectExtensionIndexRoute
}

const ConnectExtensionRouteChildren: ConnectExtensionRouteChildren = {
  ConnectExtensionFailureRoute: ConnectExtensionFailureRoute,
  ConnectExtensionSuccessRoute: ConnectExtensionSuccessRoute,
  ConnectExtensionIndexRoute: ConnectExtensionIndexRoute,
}

const ConnectExtensionRouteWithChildren =
  ConnectExtensionRoute._addFileChildren(ConnectExtensionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProRoute: ProRoute,
  SignupRoute: SignupRouteWithChildren,
  UpgradeRoute: UpgradeRoute,
  BillingManageRoute: BillingManageRoute,
  ConnectExtensionRoute: ConnectExtensionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
